const projects={
rocketman:{index:'01 / 06',title:'Rocketman',lead:'A theatrical key visual built to feel unmistakably Elton—bold, luminous and instantly legible from a distance.',tags:['Key visual','Poster','Campaign system'],brief:'Create a photorealistic campaign identity for a musical biography that communicates spectacle, music and personality while keeping the title dominant across every format.',approach:'A concentrated purple light world, orbital movement and oversized typography make the artwork feel cinematic. The system was planned from the beginning for portrait, landscape and large-format adaptations.'},
redfood:{index:'02 / 06',title:'Redfood Nature',lead:'A premium supplement range made clearer, calmer and more confident at shelf level.',tags:['Packaging','Product range','Art direction'],brief:'Translate an established collagen product into a new box and stickpack system without losing recognition, while improving hierarchy and premium appeal.',approach:'A restrained petrol-and-turquoise palette, generous negative space and a clear information structure create continuity across formats. Icons and dosage information remain easy to scan.'},
bafa:{index:'03 / 06',title:'BAFA Afrika',lead:'Editorial communication that turns international connection into one clear visual idea.',tags:['Editorial','Brochure','Brand communication'],brief:'Present an organisation connecting African SMEs with German companies in a way that feels credible, modern and relevant to a business audience.',approach:'Contrasting typography and a direct visual bridge create the core narrative. The cover language expands into a flexible editorial system for information-dense pages.'},
darling:{index:'04 / 06',title:'Architects’ Darling',lead:'A personal invitation designed to make an industry award feel selective before the event begins.',tags:['Invitation','Event design','Print'],brief:'Develop a modern, exclusive invitation with a strong sense of occasion, space for personalisation and a format efficient enough for production.',approach:'The trophy silhouette becomes structure rather than decoration. Bold scale, controlled colour and disciplined typography give the compact gatefold format a confident ceremonial character.'},
grillhaus:{index:'05 / 06',title:'Marienfelder Grillhaus',lead:'A lively family of sales materials built around appetite, speed and local character.',tags:['Menu system','Flyer','Loyalty card'],brief:'Create a coherent visual system across a DIN-long flyer, a large menu and a bonus card—clear enough for fast ordering and distinctive enough to build recognition.',approach:'A direct purple-and-orange palette, energetic type hierarchy and modular product structure keep a large amount of content easy to navigate without losing personality.'},
teekontor:{index:'06 / 06',title:'Cuxhavener Teekontor',lead:'A flexible label family with a quiet premium feel and a clear connection to the coast.',tags:['Packaging','Labels','Product family'],brief:'Modernise several tea labels for kraft pouches while keeping the range cohesive, the individual flavours easy to distinguish and the product information readable.',approach:'Layered wave lines, balanced typography and product-specific colour coding create a repeatable system. The design respects the natural packaging while adding stronger shelf presence.'}
};
const order=Object.keys(projects);const dialog=document.querySelector('.case-dialog');let activeProject=order[0];
function openProject(key){const item=projects[key];if(!item)return;activeProject=key;dialog.dataset.theme=key;dialog.querySelector('.case-index').textContent=item.index;dialog.querySelector('#case-title').textContent=item.title;dialog.querySelector('.case-lead').textContent=item.lead;dialog.querySelector('.case-brief').textContent=item.brief;dialog.querySelector('.case-approach').textContent=item.approach;dialog.querySelector('.case-tags').innerHTML=item.tags.map(tag=>`<span>${tag}</span>`).join('');if(!dialog.open)dialog.showModal();document.body.classList.add('modal-open');dialog.scrollTop=0}
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>openProject(button.dataset.project)));
dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));dialog.querySelector('.next-project').addEventListener('click',()=>openProject(order[(order.indexOf(activeProject)+1)%order.length]));dialog.querySelector('.case-footer a').addEventListener('click',()=>dialog.close());
const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('nav');const header=document.querySelector('.site-header');let lastScroll=0;
toggle.addEventListener('click',()=>{const open=toggle.classList.toggle('active');nav.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close menu':'Open menu')});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');toggle.classList.remove('active');toggle.setAttribute('aria-expanded','false')}));window.addEventListener('scroll',()=>{const current=window.scrollY;header.classList.toggle('hidden',current>lastScroll&&current>120);lastScroll=current},{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element));document.getElementById('year').textContent=new Date().getFullYear();
